# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: rtl_433 add-on
version: "latest"
slug: rtl_433
description: runs rtl_r33, typically as an MQTT client
url: "https://github.com/joshpearce/rtl_433_addon"
arch:
  # - armhf
  # - armv7
  # - aarch64
  - amd64
  # - i386
init: false
usb: true
map:
  - addon_config:r
options:
  rtl_433_arg_str: "-h"
schema:
  rtl_433_arg_str: "str?"
image: "ghcr.io/joshpearce/{arch}-ha_rtl_433_addon"
